task:
    regression
model_class:
    ModelCatBoostRegressor
model_params:
    thread_count: -1
    n_estimators: 10000
    learning_rate: 0.1
    # num_leaves: 34
    # colsample_bytree: 0.9497036
    # subsample: 0.8715623
    # max_depth: 8
    # reg_alpha: 0.041545473
    # reg_lambda: 0.0735294
    # min_split_gain: 0.0222415
    # min_child_weight: 39.3259775
    # silent: -1
    verbose: -1
    # random_state: 2019
    depth: 10
    colsample_bylevel: 0.5
    early_stopping_rounds: 300
    l2_leaf_reg: 18
    random_seed: 42
    use_best_model: True
